### ISSUE TITLE
netifaces error

### ISSUE THREAD

**Issue by knaackville** [scyto/multicast-relay#1]
Hi there!

Attempting to install this, but running into an error when running the commands on the UDM Pro (using podman in place of docker).  

podman run --rm -it --network=host -e OPTS="--verbose --noMDNS" -e INTERFACES="br2 br3 br10" scyto/multicast-relay

After running the above, I see the following:
starting multicast-relay
Using Interfaces: br2 br3 br10
Using Options --foreground  --verbose
Traceback (most recent call last):
  File "./multicast-relay/multicast-relay.py", line 801, in <module>
    sys.exit(main())
  File "./multicast-relay/multicast-relay.py", line 758, in main
    logger            = logger)
  File "./multicast-relay/multicast-relay.py", line 182, in __init__
    self.nif = Netifaces(homebrewNetifaces, ifNameStructLen)
  File "./multicast-relay/multicast-relay.py", line 72, in __init__
    import netifaces
ImportError: No module named netifaces

Any thoughts?  Thanks in advance!

**Comment by scyto** [comment]
thanks, good catch, that will teach me to forget to delete old images before doing podman run :-)

seems alpine deprecated py-netiface and updated to to py3-netiface and aliased it to the original (so i didn't get a build break)

i updated the image to python3 instead of python, should be good to go now (i think i tested on my UDMP right this time!), can you verify and if it is ok close this once verified or let me know if it is still throwing the error?

**Comment by knaackville** [comment]
That did it.  Thanks so much!  Closing the issue.
