### ISSUE TITLE
Compressing logfile 

### ISSUE THREAD

**Issue by kptkip** [scyto/multicast-relay#13]
I have the problem that the internal storage of my UDM-Pro is bloated with a vast amount of logfile data, when MDNS is activsated and some devices produce traffic. Because of this my UDM-Pro hangs completely every 2 month.

The logfile (ctrl.log) from this multicast-relay container becomes quickly 10GB size of uncompressed ASCII-file.

It would be great to have a logrotate and compressed old logfile data on a regular basis.

That would be great.

**Comment by scyto** [comment]
I could remove the verbose option if that would help?

other solutions:
1. map the logfile to your host storage and implement log rotate on the host
2. feel free to create a PR for the changes

**Comment by McSwindler** [comment]
I was having the same problem.
There's a [handy script](https://github.com/boostchicken-dev/udm-utilities/tree/master/container-common) for on_boot.d that'll set a max log size for podman containers.

Or you can set it manually in `/etc/containers/libpod.conf`, look for `max_log_size = -1` and set it to something more reasonable, like `104857600` for 100MB (this is exactly what the script does, but will reapply it on boot in case it gets overridden)

**Comment by kptkip** [comment]
@scyto @McSwindler tnx for your input!
I'll try both and give feedback in 2-3 weeks after observation ;-)

**Comment by scyto** [comment]
> @scyto @McSwindler tnx for your input! I'll try both and give feedback in 2-3 weeks after observation ;-)

no problem, tbh i don't know why i enabled verbose by default, in retrospect that was pretty stupid, i will try to correct and republish at the weekend.

**Comment by scyto** [comment]
despite what my docs say, my code shows that --verbose is not enabled by default....  but can you check with podman the full entry point used to run the container (podman container inspect should tell you)

nor should it be saving to any form of file by default if --logfile is not specified
as such all logging should just be going to stderr

unless the container (and thus alans multicast relay) has change defaults to log to file or verbose there is nothing for me to change as what you are seeing is *unifi* choice on what do about logging stderr

@McSwindler take a deeper look at what is going on your install because i don't understand it.  what command line options were you using?

**Comment by McSwindler** [comment]
By default the podman containers will log to /mnt/data/podman/storage/over-containers/*/userdata/ctr.log
And I had enabled the verbose option to debug some issues I had. Can't remember what it was exactly, but wasn't an issue with this service.

**Comment by scyto** [comment]
ok, I made sure the verbose option is not set in the image and pushed let me know if this fixes the default verbosity

in terms of podman logging this is external to this container and log rotation can be handled by whatever external log rotation folks want

this will have implictly updated to latest version of multi-cast relay from alan, please let me know if there issues in a new issue/
