### ISSUE TITLE
noTransmitInterfaces, ifFilter… Confusion

### ISSUE THREAD

**Issue by commiepinko** [scyto/multicast-relay#7]
I have multi-cast relay up and running on a UniFi UDMP, thanks to boost chicken’s excellent on-boot-script. However, I've been unable to get it to do what I want, likely due to a lack of expertise.

I have a main LAN which hosts shared services, and multiple VLANs I would like to access it. The VLANs however, should not broadcast to other VLANs. In sum, VLAN clients should see only broadcasts from the LAN, and not those from other VLANs. I've tried dozens of configurations using noTransmitInterfaces and ifFilter, to no avail.

Thanks for any tips you care to provide.

**Comment by commiepinko** [comment]
Ah - thanks.  Every day has its "duh" moment.

However, when I run…
```
podman run -it -d \
--restart=always \
--name="multicast-relay" \
--network=host \
-e INTERFACES="br0 br101 br102 br103 br104 br105 br106 br107 br108 br109" \
-e OPTS="--verbose --noTransmitInterfaces br101 br102 br103 br104 br105 br106 br107 br108 br109" \
docker.io/scyto/multicast-relay
```
…I find that all mDNS from br0 (i.e. the LAN) is also blocked.  

I thought I'd try it the other way…
```
podman run -it -d \
--restart=always \
--name="multicast-relay" \
--network=host \
-e INTERFACES="br0 br101 br102 br103 br104 br105 br106 br107 br108 br109" \
-e OPTS="--verbose --ifFilter /mnt/data/on_boot.d_support/ifFilter.json" \
docker.io/scyto/multicast-relay
```
…but I get a 
`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/on_boot.d_support/ifFilter.json'
`
error no matter what path I give **ifFilter**, or what syntax I use to specify it.

Again, thanks for taking the time to help with this.

**Comment by scyto** [comment]
Well of course MDNS is blocked, you configured the interfaces to not allow replies, MDNS needs to listen and reply on broadcast - its a 2 way protocol.

Most people miss that vlans are not a boundary of security, just a boundary of management and that if you have one port open it's no better than 65k ports open - you have openning between your isolated networks.  I spent 5 years trying to work out how we could securely allow traffic between two network domain levels of govt security and the basics was - there is no way to do it securely.

But who am i to argue with the received wisdom that vlans act as a boundary of security.

I don't run this proxy, i have my music / tv devices on my main network as that has zero difference compared to having them on a IoT vlan and letting them talk back into the LAN network.  I do have a VLAN for my cameras because they are outside the house, they are able to talk to the NAS which has a port on that VLAN and nothing else - i wont route or proxy.  Not trying to be rude, tbh you are on may be on a fools errand in terms of thinking you are making something secure.... but to quote the dude "thats just like my opinion, man" ;-)

**Comment by commiepinko** [comment]
Thanks.  I'll take your advice.
